server:
  address: localhost
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dlsgud*132
    url: jdbc:mysql://localhost:3306/fly_user

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    jwt:
      secret: secret

logging:
  level:
    root: info
  file:
    path: ${user.home}/logs
    name: fly_user.log



#    oauth2:
#      client:
#        registration:
#          google:
#            clientId:
#            clientSecret:
#          facebook:
#            clientId:
#            clientSecret:
#            redirectURI:
#          github:
#            clientId:
#              clientSecret:
#              redirectURI:
#              scope:
#
#        provider:
#          facebook:
#            authorizationURI:
#            tokenURI:
#            userInfoURI:



